version: "3"
services:
  standalone-chrome:
    image: selenium/standalone-chrome:latest
    container_name: standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_OVERRIDE_MAX_INSTANCES=true
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
networks:
  default:
    name: jenkins_compose_automation_network
    external: true