version: "3"
services:
  standalone-chrome:
    image: selenium/standalone-chrome:latest
    container_name: standalone-chrome
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
networks:
  default:
      name: jenkins_compose_automation_network
      external: true